apiVersion: apps/v1
kind: Deployment
metadata:
  name: zlodowy-backend
  namespace: zlodowy
  labels:
    app: zlodowy-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zlodowy-backend
  template:
    metadata:
      labels:
        app: zlodowy-backend
    spec:
      containers:
      - name: backend
        image: zlodowy-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: zlodowy-secrets
              key: OPENAI_API_KEY
        - name: CORS_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: zlodowy-config
              key: CORS_ORIGINS
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: zlodowy-config
              key: LOG_LEVEL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always 